// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace THHBT2324.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("THHBT2324.Models.THH286Person", b =>
                {
                    b.Property<string>("THH286ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("THH286DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("THH286Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("THH286ID");

                    b.ToTable("THH286Person");
                });
#pragma warning restore 612, 618
        }
    }
}
